# Generated by Django 5.1.4 on 2024-12-24 04:56

import cms_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('network', models.CharField(max_length=18)),
                ('version', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('country_code_iso3', models.CharField(max_length=3)),
                ('country_capital', models.CharField(blank=True, max_length=100, null=True)),
                ('country_tld', models.CharField(max_length=10)),
                ('continent_code', models.CharField(max_length=2)),
                ('in_eu', models.BooleanField(default=False)),
                ('postal', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(max_length=50)),
                ('utc_offset', models.CharField(max_length=10)),
                ('country_calling_code', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=100)),
                ('country_area', models.FloatField()),
                ('country_population', models.BigIntegerField()),
                ('asn', models.CharField(max_length=50)),
                ('org', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cms_app.models.upload_articles)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to=cms_app.models.upload_file)),
                ('size', models.CharField(blank=True, max_length=16, null=True)),
                ('type', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_file', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_file', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('agent', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipaddressdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipaddress_detail_visitor', to='cms_app.ipaddressdetail')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
